{
 "title": "Enhanced Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests per Second (RPS) [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler!=\"/metrics\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status!~\"5..\"}[1m])) / sum(rate(http_requests_total[1m])) * 100",
     "legendFormat": "Availability (%)"
    }
   ]
  },
  {
   "title": "Latency (P50, P90, P95, P98, P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket{handler=\"/\"}[1m]))",
     "legendFormat": "{{handler}} - P50"
    },
    {
     "expr": "histogram_quantile(0.90, rate(http_request_duration_seconds_bucket{handler=\"/\"}[1m]))",
     "legendFormat": "{{handler}} - P90"
    }
   ]
  },
  {
   "title": "HTTP Errors by Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{status=~\"5..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m]))\r\n/\r\nsum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Memory Usage" }
   ]
  }
 ]
}